name = "Chloe"
uuid = "ca11047d-399f-4cb1-8477-165950ce0018"
authors = ["Ian Small <ian.small@uwa.edu.au>", "Ian Castleden <ian.castleden@uwa.edu.au>"]
version = "0.1.3"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaWebAPI = "480116ec-64ea-5dec-baca-db6b11e96e37"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"
